<?php
	$this->slideshow_template = 'slideshow_basic.phtml';

	$this->links = array(
		new Link('Home', 'home', 'index.php'),
		new Link('The Soloist', 'soloist', 'soloist.php'),
		new Link('Notredame', 'notredame', 'notredame.php'),
		new Link('Videos', 'videos', 'videos.php'),
		new Link('Reviews', 'reviews', 'reviews.php'),
		new Link('Classes', 'classes', 'classes.php'),
		new Link('Contact Us', 'contact', 'contact.php'),
	);
	
	$this->render('header.phtml');
?>

<body class="<?=$this->page_id?>">
<div id="page-container">

	<div id="header">
	
		<!-- Navigation links -->
		<div class="navigation" id="main_nav">
			<ul>
				<?php foreach ($this->links as $link): ?>
					<li id="<?=$link->style_id?>"><a href="<?=$link->link?>"><?=$link->name?></a></li>
				<?php endforeach; ?>
			</ul>
		</div>

		<div id="slideshow" class="slideshow">
			<?php foreach ($this->slides as $slide): ?>
				<img src="<?=$slide?>" width="760" height="548"/>
			<?php endforeach; ?>
		</div> <!-- End of slideshow -->
		
		<div id="logo" OnClick="document.location='index.php'">
			<noscript><a href="index.php"></noscript>
			<img src="resources/images/icons/logo.png" width="200" height="75"/>
			<noscript></a></noscript>
		</div>
		
	</div> <!-- End of header -->
	
	<div id="content"> <!-- Content -->
		
		<div class="article transbox">
		<div class="padding">
			<h2>Contacting HINGED</h2><br>
			<table cellpadding="5">
				<tr><td>CHOREOGRAPHER</td><td><b>Taira Foo</b></td><td>079 6978 0063</td></tr>
				<tr><td>DIRECTOR</td><td><b>Chris Lennon</b></td><td>079 6978 0063</td></tr>
			</table>
		</div></div>
			
		<div class="article transbox">
		<div class="padding">
			<h2>Send us a message</h2><br>
			<form action="send_mail.php" method="post">
			<table>
				<tr>
					<td align="right">Your Email:</td>
					<td><input type="text" name="email_address" value="" maxlength="100" size="32" /></td>
					<td align="right">Send to:</td>
					<td>
						<select name="to_address">
							<option value="choreo">choreo</option>
							<option value="drama">drama</option>
							<option value="webadmin">webadmin</option>
						</select>
					</td>
					<td align="right"><input type="submit" value="Submit" disabled="disabled" style="background-color: darkgrey" /></td>
				</tr>
				<tr valign="top">
					<td align="right">Message:</td>
					<td colspan="4"><textarea rows="10" cols="50" name="comments" disabled="disabled" style="background-color: darkgrey">Text input disabled.</textarea></td>
				</tr>
			</table>
			</form>
		</div></div>
	</div> <!-- End of Content -->
	
<?php
	$this->render('footer.phtml');
?>
