<?php
	$this->slideshow_template = 'slideshow_basic.phtml';

	$this->links = array(
		new Link('Home', 'home', 'index.php'),
		new Link('The Soloist', 'soloist', 'soloist.php'),
		new Link('Notredame', 'notredame', 'notredame.php'),
		new Link('Videos', 'videos', 'videos.php'),
		new Link('Reviews', 'reviews', 'reviews.php'),
		new Link('Classes', 'classes', 'classes.php'),
		new Link('Contact Us', 'contact', 'contact.php'),
	);
	
	$this->render('header.phtml');
?>

<body class="<?=$this->page_id?>">
<div id="page-container">

	<div id="header">
	
		<!-- Navigation links -->
		<div class="navigation" id="main_nav">
			<ul>
				<?php foreach ($this->links as $link): ?>
					<li id="<?=$link->style_id?>"><a href="<?=$link->link?>"><?=$link->name?></a></li>
				<?php endforeach; ?>
			</ul>
		</div>

		<div id="slideshow" class="slideshow">
			<?php foreach ($this->slides as $slide): ?>
				<img src="<?=$slide?>" width="760" height="548"/>
			<?php endforeach; ?>
		</div> <!-- End of slideshow -->
		
		<div id="logo" OnClick="document.location='index.php'">
			<noscript><a href="index.php"></noscript>
			<img src="resources/images/icons/logo.png" width="200" height="75"/>
			<noscript></a></noscript>
		</div>
		
	</div> <!-- End of header -->
	
	<div id="content"> <!-- Featured Content -->
		<div style="text-align: center; margin: 25px;">
			Welcome to the HINGED dance company website. Enjoy your stay.
		</div>
		
		<div class="article transbox">
		<div class="padding" style="text-align: justify">
		<p>HINGED - A new contemporary dance company that hopes to dedicate its
works to those who are, living under extreme circumstances and
aspiring to reach greater heights and achieve their goals.  The
company aims to move audiences from one state to another - through
fierce, energetic and strong movement, to more touching, heartfelt
moments of connection between the performers. 'HINGED' is a story-based
company that pushes the boundaries of contemporary dance.</p>
<p>Foo's choreography uses intricate gestures and it moves through the
space with a seamless racing energy.  The athletic, fast-paced
choreography contrasts well with intervals of stillness and moments of
weightlessness. The angular movement takes the audience from one
emotional state to another, through fluid transitions, shifting from
the floor to standing within a split second &ndash; riveting the audience to
both the story and the pure movement phrases of the choreography.</p>
<p>There is a strong sense of honesty in the choreography; although
introverted and asymmetrical it creates appropriate emotions and
progresses the story through its different scenes.  The piece will be
an abstract telling of the story through dance using subtle gestures
to narrate, but also to allow the audience to find their own emotional
journey.</p>
		</div></div>
		
		<?php if ($this->featured): ?>
			<div class="article transbox">
			<div class="padding">
				<h2><?=$this->featured->title?></h2>
				<p><?=$this->featured->summary1?></p>
				<?php if ($this->featured->videogroup): ?>
					<!-- If the video list is marked as "flashonly", don't use html5 video tag,
						 just embed first video directly as flash -->
					<?php if ($this->featured->videogroup->type == VIDEO_LINK): ?>
						<embed src="<?=$this->featured->videogroup->videos->location?>" type="application/x-shockwave-flash" width="560" height="315" allowscriptaccess="always" allowfullscreen="true"></embed>
					<?php else: ?>
						<!-- Otherwise use html5 video tag as normal (use any flash urls as fallback) -->
						<video width="480" height="270" controls="controls" poster="images/notredame_still.png">
						
						<?php foreach ($this->featured->videogroup->videos as $video): ?>
							<?php if ($video->type != FLASH): ?>
								<source src="<?=$video->location?>" type="<?=$video->type?>" />
							<?php else: ?>
								<embed src="<?=$video->location?>" type="application/x-shockwave-flash" width="560" height="315" allowscriptaccess="always" allowfullscreen="true">
									Bad browser!
								</embed>
							<?php endif; ?>
						<?php endforeach; ?>
						
						</video>
					<?php endif; ?>
				<?php endif; ?>
				<?php if ($this->featured->summary2): ?>
					<p><?=$this->featured->summary2?></p>
				<?php endif; ?>
			</div></div>
		<?php endif; ?>
	</div> <!-- End of Featured Content -->
	
	<div id="content">	<!-- New Content -->
		<!-- List of homepage articles -->
		<?php foreach ($this->articles as $article): ?>
			<div class="article transbox summary"
				<?php if ($article->link): ?>
					OnClick="document.location='<?=$article->link?>'"
				<?php endif; ?>
			>
			<div class="padding">
			<?php if ($article->link): ?>
				<noscript><a href="<?=$article->link?>"></noscript>
			<?php endif; ?>
				<?php if ($article->thumbnail): ?>
					<img src="<?=$article->thumbnail?>" alt="Thumbnail" />
				<?php endif; ?>
				<h2><a>
					<?=$article->title?>
				</a></h2>
				<p>
					<?=$article->summary?>
				</p>
				<?php if ($article->link): ?>
					<a>More...</a>
					<noscript></a></noscript>
				<?php endif; ?>
			</div></div>
		<?php endforeach; ?>
	</div> <!-- End of New Content -->
	
<?php
	$this->render('footer.phtml');
?>
