<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
	<title><?=$this->title?></title>
	
	<meta http-equiv="Content-type" content="text/html; charset=UTF-8" />
	<meta http-equiv="Content-Language" content="en-us" />
	<meta http-equiv="imagetoolbar" content="no" />
	
	<meta name="MSSmartTagsPreventParsing" content="true" />
	<meta name="description" content="Description" />
	<meta name="keywords" content="Keywords" />
	<meta name="author" content="Fradgers" />
	
	<link rel="stylesheet" href="css/master.css">
	<!-- <link rel="stylesheet" href="css/ie7.css"> -->

	<!-- include jQuery library and Cycle slideshow plugin -->
	<script type="text/javascript" src="scripts/jquery.min.js"></script>
	<script type="text/javascript" src="scripts/jquery.cycle.all.latest.js"></script>
	
	<!-- Cycle slideshow settings -->
	<script type="text/javascript">
	$(document).ready(function() {
    $('.slideshow').cycle({
		fx:     'scrollHorz',
		prev:   '#prev',
		next:   '#next',
		timeout: 4000,
		speed: 2000,
		pause: 1
	});
	});
	</script>
</head>

<body class="<?=$this->page_id?>">
<div id="page-container">

	<div id="header">
	
		<!-- Navigation links -->
		<div class="navigation" id="main_nav">
			<ul>
				<?php foreach ($this->links as $link): ?>
					<li id="<?=$link->style_id?>"><a href="<?=$link->link?>"><?=$link->name?></a></li>
				<?php endforeach; ?>
			</ul>
		</div>

		<div id="slideshow" class="slideshow">
			<?php foreach ($this->slides as $slide): ?>
				<img src="<?=$slide?>" width="760" height="548"/>
			<?php endforeach; ?>
		</div> <!-- End of slideshow -->
		
		<div id="logo" OnClick="document.location='index.php'">
			<noscript><a href="index.php"></noscript>
			<img src="resources/images/icons/logo.png" width="200" height="75"/>
			<noscript></a></noscript>
		</div>
		
	</div> <!-- End of header -->
	
	<div id="content">
	
		<!-- Collection of show content -->
		<?php foreach ($this->contents as $content): ?>
			<div class="article transbox">
			<div class="padding">
				<h2><?=$content->title?></h2>
				<p><?=h($content->summary1)?></p>
				<?php if ($content->videogroup): ?>
					<!-- If the video list is marked as "flashonly", don't use html5 video tag,
						 just embed first video directly as flash -->
					<?php if ($content->videogroup->type == VIDEO_LINK): ?>
						<embed src="<?=$content->videogroup->videos->location?>" type="application/x-shockwave-flash" width="560" height="315" allowscriptaccess="always" allowfullscreen="true"></embed>
					<?php else: ?>
						<!-- Otherwise use html5 video tag as normal (use any flash urls as fallback) -->
						<video width="480" height="270" controls="controls" poster="resources/images/notredame_still.png">
						
						<?php foreach ($content->videogroup->videos as $video): ?>
							<?php if ($video->type != FLASH): ?>
								<source src="<?=$video->location?>" type="<?=$video->type?>" />
							<?php else: ?>
								<embed src="<?=$video->location?>" type="application/x-shockwave-flash" width="560" height="315" allowscriptaccess="always" allowfullscreen="true">
									Bad browser!
								</embed>
							<?php endif; ?>
						<?php endforeach; ?>
						
						</video>
					<?php endif; ?>
				<?php endif; ?>
				<?php if ($content->summary2): ?>
					<p><?=h($content->summary2)?></p>
				<?php endif; ?>
			</div></div>
		<?php endforeach; ?>

		<!-- End of list of homepage articles -->
		
	</div> <!-- End of content -->
	
	<div id="footer">
	
		<div id="altnav"> -
			<?php foreach ($this->links as $link): ?>
				<a href="<?=$link->link?>"><?=$link->name?></a> -
			<?php endforeach; ?>
		</div>
		Copyright &copy; HINGED
		
	</div> <!-- End of footer -->

</div> <!-- End of page-container -->
</body>

</html>